name: movies_app
description: A Movies App using TMDB API
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.3.1               
  retrofit: ^4.0.1
  json_annotation: ^4.9.0
  provider: ^6.0.5
  sqflite: ^2.2.8
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  retrofit_generator: ^10.0.2
  json_serializable: ^6.10.0
  analyzer: ^8.1.1

flutter:
  uses-material-design: true

  assets: